#!/usr/bin/env bash

# diffExcel
# echo "1=$1,2=$2,3=$3,4=$4,5=$5,6=$6,7=$7,8=$8,9=$9"

mono /Users/a3/ws/excel_tools/ExcelDiff/bin/Debug/ExcelDiff.exe $1 $2

# mono /Users/a3/.bin/excel/ExcelDiff.exe $1 $2

