#!/bin/sh

## start http:80
function StartHttp80()
{
    echo "start http ..."
    mkdir -p ~/http
    pushd ~/workspace
    killN http.server > /dev/null
    nohup sudo python3 -m http.server 80 > ~/http/nohup.http 2>&1 &
    popd
    echo "start http end $?\n"
}


########## main ########## 

StartHttp80

